package org.drools.test;


import org.drools.fipa.body.content.Action;
import org.kmr2.decision.*;



rule "Action_Request : advanceDiagnosticGuideProcess"
when
    $a  : Action( actionName == "advanceDiagnosticGuideProcess",
                  $userId      : this["userId"],
                  $patientId   : this["patientId "],
                  $dxProcessId : this["dxProcessId"]
                )
    $dx : DiagnosticGuideProcess( id == $dxProcessId, status == "Started", $steps : diagnosticProcessHistory )
    $cd : DxDecision( this memberOf $steps, current == true )
then
    System.out.println( "****************************************************************************************************************** ");
    System.out.println( "******************************************************************** Stepping to " + ($steps.size()) );
    retract( $cd );
    insert( new DxStep( $dx.getId(), ($steps.size()) ) );
    retract( $a );
end


query advanceDiagnosticGuideProcess( String $userId, String $patientId, String $dxProcessId, String $return )
    $return := DiagnosticGuideProcess( id == $dxProcessId )
end
