package org.drools.test;


import org.drools.fipa.body.content.Action;
import org.kmr2.decision.*;



rule "Action_Request : completeDiagnosticGuideProcess - Complete"
when
    $a  : Action( actionName == "completeDiagnosticGuideProcess",
                  $userId      : this["userId"],
                  $patientId   : this["patientId "],
                  $dxProcessId : this["dxProcessId"],
                  $status      : this["status"] == "Complete"
                )
    $dx : DiagnosticGuideProcess( id == $dxProcessId, status == "Started", $steps : diagnosticProcessHistory )
then
    $dx.setStatus( "Complete" );
    update($dx);
    retract( $a );
end

rule "Action_Request : completeDiagnosticGuideProcess - Cancel"
when
    $a  : Action( actionName == "completeDiagnosticGuideProcess",
                  $userId      : this["userId"],
                  $patientId   : this["patientId "],
                  $dxProcessId : this["dxProcessId"],
                  $status      : this["status"] == "Cancel"
                )
    $dx : DiagnosticGuideProcess( id == $dxProcessId, status == "Started" )
then
    retract( $dx );
    retract( $a );
end

query completeDiagnosticGuideProcess( String $userId, String $patientId, String $dxProcessId, String $status, String $return )
    $return := String() from "ok"
end
