
package org.kmr2.decision;

declare DiagnosticGuideProcess
   id           : String                @key
   status       : String                        = "n/a"
   decModel     : String
   diagModel    : String
   steps        : java.util.LinkedList
   actions      : java.util.HashSet
end


declare DxDecision
    nodeId      : String                @key
    step        : int
    current     : boolean
    descr       : String
    disease     : int
    response    : String
    children    : java.util.List
end



declare DxActionTemplate
    actId       : String                @key
    descr       : String
end


declare DxAction
    actId       : String                @key
    descr       : String
    utility     : double
    utilityLing : String
    status      : String                        = "Not Started"
    update      : java.util.Date
    form        : org.drools.informer.presentation.SurveyGUIAdapter
end


declare DxStep
    dxProcessId : String
    step        : int
end