 package org.drools.test;



import org.drools.fipa.body.content.Action;
import org.drools.fipa.MessageContentEncoder;
import org.drools.fipa.Encodings;

import org.drools.informer.*;
import org.drools.informer.xml.ChangeCollector;
import org.drools.informer.presentation.*;

import org.drools.interaction.*;

import org.drools.io.internal.InternalResource;
import java.util.List;
import java.util.ArrayList;

import org.drools.pmml_4_0.ModelMarker;
import org.drools.pmml_4_0.PMML4Field;
import org.drools.pmml_4_0.PMML4Wrapper;

import org.kmr2.decision.*;
import org.kmr2.risk.*;



rule "Action_Request : getRiskModelsDetail"
when
    $a :  Action( actionName == "getRiskModelsDetail",
                  $userId    : this["userId"],
                  $patientId : this["patientId"],
                  $modelIds  : this["modelIds"]
                )
    not   GetRiskModelsDetail()
then
    GetRiskModelsDetail ans = new GetRiskModelsDetail();
    insert(ans);
end


rule "Action_Request : getRiskModelsDetail - refresh"
no-loop
when
    $a :  Action( actionName == "getRiskModelsDetail",
                  $userId    : this["userId"],
                  $patientId : this["patientId"],
                  $modelIds  : this["modelIds"]
                )
    $g : GetRiskModelsDetail( )
then
    $g.setModelIds( java.util.Arrays.asList( (String[]) $modelIds ) );
    $g.setRiskModels( new ArrayList() );
    $g.setSuccessStatus( true );
    update( $g );
end



rule "Action_Request : getRiskModelsDetail - init Models"
when
    $a :  Action( actionName == "getRiskModelsDetail",
                  $userId    : this["userId"],
                  $patientId : this["patientId"],
                  $modelIds  : this["modelIds"]
                )
    $id : String() from $modelIds
    not   ModelMarker( modelName == $id )
    $rs : InternalResource( name == $id )
then
    String defPack = PMML4Wrapper.getPack();
    PMML4Wrapper.setPack( "org.drools.pmml_4_0.risk."+$id );
    manager.addResource( $id, $rs );
    PMML4Wrapper.setPack( defPack );
end


rule "Action_Request : getRiskModelsDetail - model info"
when
    $mm   : ModelMarker( $id : modelName )
    $res  : InternalResource( name == $id, $descr : description )
    $grmd : GetRiskModelsDetail( $details : riskModels, modelIds contains $id )
    not     RiskModelDetail( modelId == $id )
then
    RiskModelDetail rmd = new RiskModelDetail();
        rmd.setModelId( $id );
        rmd.setTitle( $descr );
        rmd.setDisease( $descr );
    $grmd.getRiskModels().add( rmd );
    insert( rmd );
end



rule "Action_Request : getRiskModelsDetail - model info refresh"
when
    $mm   : ModelMarker( $id : modelName )
    $res  : InternalResource( name == $id, $descr : description )
    $grmd : GetRiskModelsDetail( $details : riskModels, modelIds contains $id )
    $rmd  : RiskModelDetail( modelId == $id, this not memberOf $details )
then
    $grmd.getRiskModels().add( $rmd );
    update( $rmd );
end



rule "Action_Request : getRiskModelsDetail - clear"
salience -9999
when
    $a :  Action( actionName == "getRiskModelsDetail" )
then
    retract( $a );
end



rule "Update Risk I"
when
    $fld : PMML4Field( name matches ".*Risk$"  )
then
    System.out.println(" DONNING A RISK VALUE " + $fld );
    RiskValue val = don( $fld, RiskValue.class, true );
end

rule "Update Risk II"
when
    $rmd : RiskModelDetail( $mid : modelId )
           RiskValue( context == $mid, $val : value )
then
    $rmd.setRelativeRisk( (int) Math.round( $val * 100 ) ) ;
end

rule "Update Risk III"
when
    $rmd : RiskModelDetail( $mid : modelId )
           not RiskValue( context == $mid )
then
    $rmd.setRelativeRisk( -1 ) ;
end


rule "Threshold"
when
    $rmd : RiskModelDetail( $mid : modelId )
    RiskThreshold( $mid, "Alert", $value ; )
then
    System.err.println("Setting alert thold in RiskModelDetail " + $value );
    $rmd.setAlertThreshold( $value );
end


rule "Include Survey"
when
    $rmd : RiskModelDetail( $mid : modelId )
    $qid : String() from ( $mid+"_Questionnaire" )
           ?getItemId( $qid, $mid, $surveyId ; )
//           getSurvey( $userId, $patientId, $surveyId, $return ; )
then
    $rmd.setSurveyId( $surveyId );
end


rule "Include Dx Guide"
when
    $rmd : RiskModelDetail( $mid : modelId, $dis : disease )
    $dxg : DiagnosticGuideProcess( disease == $dis, $id : id, $status : status == "Started" )
then
    $rmd.setDxProcessId( $id );
    $rmd.setDxProcessStatus( $status );
end

rule "Clear Dx Guide"
when
    $rmd : RiskModelDetail( $mid : modelId, $dis : disease )
    exists DiagnosticGuideProcess( disease == $dis, $id : id )
    not    DiagnosticGuideProcess( disease == $dis, $id : id, $status : status != "Complete" )
then
    $rmd.setDxProcessId( null );
    $rmd.setDxProcessStatus( "Complete" );
end

rule "No Dx Guide"
when
    $rmd : RiskModelDetail( $mid : modelId, $dis : disease )
    not    DiagnosticGuideProcess( disease == $dis )
then
    $rmd.setDxProcessId( null );
    $rmd.setDxProcessStatus( "Not Started" );
end







rule "Update Severity : Low"
when
    $rmd : RiskModelDetail( $mid : modelId )
           RiskValue( context == $mid, $val : value <= 0.25 )
then
    $rmd.setSeverity( "Low" );
end

rule "Update Severity : Average"
when
    $rmd : RiskModelDetail( $mid : modelId )
           RiskValue( context == $mid, $val : value > 0.25 && <= 0.50 )
then
    $rmd.setSeverity( "Average" );
end

rule "Update Severity : High"
when
    $rmd : RiskModelDetail( $mid : modelId )
           RiskValue( context == $mid, $val : value > 0.50 && <= 0.75 )
then
    $rmd.setSeverity( "High" );
end

rule "Update Severity : Very High"
when
    $rmd : RiskModelDetail( $mid : modelId )
           RiskValue( context == $mid, $val : value > 0.75 )
then
    $rmd.setSeverity( "Very High" );
end



query getRiskModelsDetail( String $userId, String $patientId, String[] $modelIds, Object $return )
    $return :=  GetRiskModelsDetail( )
end



