package org.drools.test;


import org.drools.fipa.body.content.Action;
//import org.drools.fipa.MessageContentEncoder;
//import org.drools.fipa.Encodings;

import org.drools.informer.*;
//import org.drools.informer.xml.ChangeCollector;
import org.drools.informer.presentation.*;

//import org.drools.io.internal.InternalResource;
//import java.util.List;
//import java.util.ArrayList;

//import org.drools.pmml_4_0.ModelMarker;
//import org.drools.pmml_4_0.PMML4Field;




rule "Action_Request : getSurvey"
when
    $a : Action( actionName == "getSurvey",
                 $userId : this["userId"],
                 $patientId : this["patientId"],
                 $surveyId : this["surveyId"]
               )
    not SurveyTicket( sid == $surveyId )
then
    insert( new SurveyTicket( (String) $surveyId, (String) $userId, null, false, null) );
    retract( $a );
end


query getSurvey( String $userId, String $patientId, String $surveyId, SurveyGUIAdapter $return )
    $return := SurveyGUIAdapter( $surveyId := itemId )
end
