
import org.drools.fipa.body.content.Action;

import org.drools.informer.*;
import org.drools.informer.xml.ChangeCollector;
import org.drools.informer.presentation.*;

import org.kmr2.decision.*;




rule "Action_Request : setDiagnosticActionStatus - Complete"
when
    $a  : Action( actionName == "setDiagnosticActionStatus",
                  $userId       : this["userId"],
                  $patientId    : this["patientId"],
                  $processId    : this["dxProcessId"],
                  $actionId     : this["actionId"],
                  $status       : this["status"] == "Complete"
                  )
    $dx : DxAction( questionnaireId == $actionId, status == "Started" || == "Committed" )
then
    $dx.setStatus( (String) $status );
    $dx.setStatusUpdated( new java.text.SimpleDateFormat().format( new java.util.Date() ) );
    update($dx);
end

rule "Action_Request : setDiagnosticActionStatus - Started"
when
    $a  : Action( actionName == "setDiagnosticActionStatus",
                  $userId       : this["userId"],
                  $patientId    : this["patientId"],
                  $processId    : this["dxProcessId"],
                  $actionId     : this["actionId"],
                  $status       : this["status"] == "Started"
                  )
    $dx : DxAction( questionnaireId == $actionId, status == "Not Started" )
then
    $dx.setStatus( (String) $status );
    $dx.setStatusUpdated( new java.text.SimpleDateFormat().format( new java.util.Date() ) );
    update($dx);
end

rule "Action_Request : setDiagnosticActionStatus - Committed"
when
    $a  : Action( actionName == "setDiagnosticActionStatus",
                  $userId       : this["userId"],
                  $patientId    : this["patientId"],
                  $processId    : this["dxProcessId"],
                  $actionId     : this["actionId"],
                  $status       : this["status"] == "Committed"
                  )
    $dx : DxAction( questionnaireId == $actionId, status == "Started" )
then
    $dx.setStatus( (String) $status );
    $dx.setStatusUpdated( new java.text.SimpleDateFormat().format( new java.util.Date() ) );
    update($dx);
end

rule "Action_Request : setDiagnosticActionStatus - Not Started"
when
    $a  : Action( actionName == "setDiagnosticActionStatus",
                  $userId       : this["userId"],
                  $patientId    : this["patientId"],
                  $processId    : this["dxProcessId"],
                  $actionId     : this["actionId"],
                  $status       : this["status"] == "Not Started"
                  )
    $dx : DxAction( questionnaireId == $actionId, status == "Started" )
then
    $dx.setStatus( (String) $status );
    $dx.setStatusUpdated( new java.text.SimpleDateFormat().format( new java.util.Date() ) );
    update($dx);
end


rule "Action_Request : setDiagnosticActionStatus"
salience -100
when
    $a  : Action( actionName == "setDiagnosticActionStatus" )
then
    System.out.println("Clearing setDxAction");
    retract( $a );
end



query setDiagnosticActionStatus( String $userId, String $patientId, String $processId, String $actionId, String $status, String $return )
    DxAction( questionnaireId == $actionId, $return := status )
end
