
import org.drools.fipa.body.content.Action;

import org.drools.informer.*;
import org.drools.informer.xml.ChangeCollector;
import org.drools.informer.presentation.*;

import org.drools.base.DroolsQuery;






rule "Action_Request : setSurvey"
when
    $a : Action( actionName == "setSurvey",
                 $userId : this["userId"],
                 $patientId : this["patientId"],
                 $surveyId : this["surveyId"],
                 $questionId : this["questionId"],
                 $value : this["answer"] != null
                 )

then
    retract($a);
    insert( new Answer((String) $questionId, (String) $value) );
end

rule "Action_Request : clearSurvey"
when
    $a : Action( actionName == "setSurvey",
                 $userId : this["userId"],
                 $patientId : this["patientId"],
                 $surveyId : this["surveyId"],
                 $questionId : this["questionId"],
                 $value : this["answer"] == null
                 )
then
    retract($a);
    insert( new Answer( (String) $questionId, "null" ) );
end


rule "Action_Request : setSurvey Helper"
salience 10
when
    $a : Action( actionName == "setSurvey" )
then
    insert( new ChangeCollector() );
end



query setSurvey( String $userId, String $pid, String $surveyId, String $questionId, String $value, ChangeGUIAdapter $return   )
    $return := ChangeGUIAdapter( itemId == $surveyId )
end
