
import org.drools.fipa.body.content.Action;

import org.drools.informer.*;
import org.drools.informer.xml.ChangeCollector;
import org.drools.informer.presentation.*;

import org.drools.base.DroolsQuery;






rule "Action_Request : setSurvey"
when
    $a : Action( actionName == "setSurvey",
                 $userId : this["userId"],
                 $patientId : this["patientId"],
                 $surveyId : this["surveyId"],
                 $questionId : this["questionId"],
                 $value : this["answer"]
                 )

then
    retract($a);
    Answer ans = new Answer((String) $questionId, (String) $value);
    System.err.println( ">>>>>>>>>>>>>>>>>>>>>>>>>>> " + ans );
    insert( ans );
end


rule "Action_Request : setSurvey Helper"
salience 10
when
    $a : Action( actionName == "setSurvey" )
then
    insert( new ChangeCollector() );
end


rule "Debug 1"
when
    $cx : ChangeGUIAdapter()
then
    System.out.println(" WARNING CGUI " + $cx );
end

rule "Debug"
when
    $cx : DroolsQuery( name == "setSurvey" )
then
    System.out.println(" WARNING QERY " + $cx );
end

rule "Debug 3"
when
    DroolsQuery( name == "setSurvey" )
    $cx : ChangeGUIAdapter()
then
    System.out.println(" WARNING CGUI " + $cx );
end



query setSurvey( String $userId, String $pid, String $surveyId, String $questionId, String $value, ChangeGUIAdapter $return   )
    $return := ChangeGUIAdapter( itemId == $surveyId )
end
