

/*

declare EMRToken
    id : String
end

rule "EMR"
salience 99999999
when
    FactType( $patientId : patientId.value )
    not EMRToken( id == $patientId )
then
    System.out.println( " << Initializing session >> " );
    // factService.load( $patientId )
    insert( new EMRToken( $patientId ) );
end


rule "LogEMR"
when
    EMRToken( $patientId : id )
then
    System.out.println(" << Session initialized for patient " + $patientId + " >>");
end
*/









//rule "Log"
//when
//    $o : Object()
//then
////    if ( ! $o.getClass().getPackage().getName().contains("Expect") ) {
//    System.err.println( $o );
////    }
//end






































//rule "Log"
//salience 9999
//when
//    $o : Object()
//then
//    System.out.println("PATIENT #SURVEY >>> " + $o);
//end
//
