
package org.kmr2.decision;

import org.drools.informer.generator.Surveyable;

import org.drools.informer.generator.annotations.Questionable;
import org.drools.informer.generator.annotations.QuestionMark;
import org.drools.informer.generator.annotations.AllowedAnswers;


declare DiagnosticGuideProcess
   id           : String                @key
   status       : String                        = "n/a"
   decModel     : String
   diagModel    : String
   steps        : java.util.LinkedList
   actions      : java.util.HashSet
end


declare DxDecision
    nodeId      : String                @key
    step        : int
    current     : boolean
    descr       : String
    disease     : int
    response    : String
    children    : java.util.List
end


declare Surveyable
end


declare DxAction extends Surveyable
    questionnaireId : String                @key
//    descr           : String
    utility         : double
    utilityLing     : String

    status          : String                        = "Not Started"
    @QuestionMark( type = Question.QuestionType.TYPE_TEXT, label = "Current status : ", required = true )
    @AllowedAnswers( values = { "Not Started=Not Started", "Started=Started", "Committed=Committed", "Complete=Complete" } )

    upDate          : java.util.Date

    form            : org.drools.informer.presentation.SurveyGUIAdapter
end


declare DxStep
    dxProcessId : String
    step        : int
end