
package org.kmr2.decision;

import org.drools.informer.generator.Surveyable;

import org.drools.informer.generator.annotations.Questionable;
import org.drools.informer.generator.annotations.QuestionMark;
import org.drools.informer.generator.annotations.AllowedAnswers;


declare DiagnosticGuideProcess
   id                       : String                @key
   status                   : String                        = "n/a"
   message                  : String
   decModel                 : String
   diagModel                : String
   disease                  : String
   diagnosticProcessHistory : java.util.LinkedList
   canAdvance               : boolean                       = false
   actions                  : java.util.HashSet
   successStatus            : boolean                       = true
end


declare DxDecision
    nodeId                  : String                @key
    stage                   : int
    current                 : boolean
    descr                   : String
    diseaseProbability      : int
    severity                : String
    response                : String
    actions                 : java.util.List
end


declare Surveyable
end


declare DxAction extends Surveyable

    actionId        : String                        @key
    questionnaireId : String
    numQuestions    : int

    utility         : double      = -1.0
    utilityLevel    : String

    status          : String                        = "Not Started"
//    @QuestionMark( type = Question.QuestionType.TYPE_TEXT, label = "Current status : ", required = true )
//    @AllowedAnswers( values = { "Not Started=Not Started", "Started=Started", "Committed=Committed", "Complete=Complete" } )

    statusUpdated   : String

end


declare DxStep
    dxProcessId : String
    stage       : int
end


declare DiagValue
@format(trait)
    value   : double
    context : String
end









