
package org.drools.test;

import java.util.List;


declare GetRiskModelsDetail
    userId              : String
    patientId           : String
    modelIds            : List
    riskModels          : List
    successStatus       : boolean       = false
    statusMessage       : String        = "(ok)"
end

declare RiskModelDetail
    modelId             : String
    position            : int
    severity            : int
    title               : String
    disease             : String
    relativeRisk        : int
    relativeRiskRange   : int
    alertThreshold      : int
    surveyId            : String
    dxProcessId         : String
    dxProcessStatus     : String
end


declare RiskValue
@format(trait)
    value   : double
    context : String
end


declare RiskThreshold
    modelId     : String        @key
    type        : String        @key      // "Alert" | "Display"
    threshold   : int
end



query defaultRiskThreshold( Integer $def )
    $def := Integer( ) from new Integer(50);
end

query getRiskThreshold( String $modelId, String $type, int $thold, RiskThreshold $holder )
    $holder := RiskThreshold( $modelId, $type, $thold ; )
    or
    ?defaultRiskThreshold( $thold ; )
end




